---
services:
  db:
    image: postgres:18.1
    restart: always
    environment:
      POSTGRES_USER: sportverein
      POSTGRES_PASSWORD: secret-sportverein-db-password
      POSTGRES_DB: sportverein
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql"
volumes:
  postgres-data: